//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.IT.RelationshipManagement.Interchange.Platform.Clients.Sdk.TestClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.IT.RelationshipManagement.Interchange.Platform.Clients.Sdk.TestClient.S" +
                            "tringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of Bulk Send::.
        /// </summary>
        internal static string BULK_SEND_STATUS {
            get {
                return ResourceManager.GetString("BULK_SEND_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BulkSendSummaryDetails received..
        /// </summary>
        internal static string EMAIL_TRACKING_BULK_SEND_SUMMARY_STATUS {
            get {
                return ResourceManager.GetString("EMAIL_TRACKING_BULK_SEND_SUMMARY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Tracking status received..
        /// </summary>
        internal static string EMAIL_TRACKING_STATUS {
            get {
                return ResourceManager.GetString("EMAIL_TRACKING_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TriggerSendSummaryDetails received..
        /// </summary>
        internal static string EMAIL_TRACKING_TRIGGER_SEND_SUMMARY_STATUS {
            get {
                return ResourceManager.GetString("EMAIL_TRACKING_TRIGGER_SEND_SUMMARY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEmailDetails returned {0} records..
        /// </summary>
        internal static string EmailDetails_Status {
            get {
                return ResourceManager.GetString("EmailDetails_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    And the corresponding eventID is  {0} :.
        /// </summary>
        internal static string EVENT_ID {
            get {
                return ResourceManager.GetString("EVENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFolderHierarchy returned {0} folders..
        /// </summary>
        internal static string FolderHierarchy_Status {
            get {
                return ResourceManager.GetString("FolderHierarchy_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of Limited Program ::.
        /// </summary>
        internal static string LP_Status {
            get {
                return ResourceManager.GetString("LP_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of MSI SUBSCRIBE::.
        /// </summary>
        internal static string MSI_SUBSCRIBE_STATUS {
            get {
                return ResourceManager.GetString("MSI_SUBSCRIBE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of MSI UNSUBSCRIBE::.
        /// </summary>
        internal static string MSI_UNSUBSCRIBE_STATUS {
            get {
                return ResourceManager.GetString("MSI_UNSUBSCRIBE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of Partner (Generic) ::.
        /// </summary>
        internal static string Partner_Status {
            get {
                return ResourceManager.GetString("Partner_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of requestID  {0}  : .
        /// </summary>
        internal static string REQUEST_STATUS_MESSAGE {
            get {
                return ResourceManager.GetString("REQUEST_STATUS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of TAGM :: .
        /// </summary>
        internal static string TAGM_Status {
            get {
                return ResourceManager.GetString("TAGM_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of WWE ::.
        /// </summary>
        internal static string WWE_Status {
            get {
                return ResourceManager.GetString("WWE_Status", resourceCulture);
            }
        }
    }
}
